Add Formik and Yup to Participant Search
CodeForPhilly/prevention-point pull request #380
Opened 2020-09-22 03:25 UTC by LizKalter

2020-09-22 22:58 UTC, MikeyManoguerra requested changes
I left a couple of comments, should be pretty simple.

2020-09-23 13:42 UTC, MikeyManoguerra submitted a review, later dismissed

2020-09-23 14:26 UTC, LizKalter commented
@MikeyManoguerra I'm going to need another review here. The yarn.lock file had a conflict. Thanks.

2020-09-23 23:38 UTC, MikeyManoguerra approved these changes

2020-09-24 00:15 UTC, merged