Update django admin
CodeForPhilly/prevention-point pull request #419
Opened 2020-10-20 23:36 UTC by JackRyan1989

Updated SEP_data, Behavioral_Health_Note and HCV_Note models in addition to changing the models listed in admin.py.

2020-10-22 14:51 UTC, MikeyManoguerra commented on core/sep_data/views.py
>  class Sep_DataViewSet(ModelViewSet):
Update the view to match the model name

2020-10-22 14:51 UTC, MikeyManoguerra commented on core/sep_data/serializers.py
>  class Sep_DataSerializer(serializers.ModelSerializer):
Update the serializer to match the model name

2020-10-22 15:06 UTC, MikeyManoguerra requested changes
Looks good! Just a Small naming change.

While looking at the branch, I was reminded you can customize the link in the admin by defining the `__str__` method on the model class. You can see an example on the Visit model.

Lets get this merged in and we can open  a separate  issue for that.

https://docs.djangoproject.com/en/3.1/ref/models/instances/#django.db.models.Model.__str__

2020-10-22 15:12 UTC, JackRyan1989 reviewed
Updated admin.py, sep data model, behavioral health notes model, hcv notes model along with the sep data view and serializer.

2020-10-26 20:31 UTC, JackRyan1989 reviewed
Reviewed and addressed

2020-10-27 00:39 UTC, MikeyManoguerra approved these changes
Looks good, Thanks for the final changes

2020-10-27 12:50 UTC, merged