Participation form validation 426
CodeForPhilly/prevention-point pull request #436
Opened 2020-11-17 00:38 UTC by JackRyan1989

Schema validation ready for review.

2020-11-18 21:57 UTC, MikeyManoguerra commented
hey hang tight for a minute, i want to merge these in one at time bc there was some overwriting going on

2020-11-20 02:59 UTC, MikeyManoguerra commented on frontend/src/validation/index.js
> +  if (inputSchema === "visitSchema") {
i like this.

Can you make constants for the schema names?  `const VISIT_SCHEMA = 'VISIT_SCHEMA'` and then import it from here to the visitRouter/index.

2020-11-20 03:12 UTC, MikeyManoguerra commented on frontend/src/validation/index.js
> +  date_of_birth: Yup.string().required(),
Id like to make these dates valid for a reasonable period, between 1900 and today. i messed around with it and we have to turn the date string back into a date object, or extend the schema and handle it ourselves. 

idea is to add a new case to handleParticipant update fn, that just dumps the date string `yyyy-MM-dd` into new Date(),  then update this to yup.date() with min and max.

i tested it and it submitted successfully to the back end, though it seems a little silly? /shrug

2020-11-20 03:14 UTC, MikeyManoguerra requested changes
looks good. the one thing for sure i want is the constants. we can talk about the date validation if you like. 

Just a heads up, there is another participant form in existing participant view. if you can add that here without to much trouble, that woudl be cool, otherwise we do it later.

also, rebase.

2020-11-20 15:35 UTC, JackRyan1989 commented
@MikeyManoguerra So I'm running into a slight issue when validating the existing participant form. When creating a participant the 'insurer' field is an empty string when 'is_insured' is set to false, otherwise it is a number. However, on for an existing participant you can set the 'is_insured' field to false, but the 'insurer' field can remain as a number. I'm not sure if we should pursue setting the 'insurer' field to an empty string when 'is_insured' is false or if I should try some clever work around for validation, thoughts?

2020-11-20 16:37 UTC, JackRyan1989 commented
@MikeyManoguerra So actually there's a tricky thing in general which is that when you are creating a new participant or changing a field on an existing participant the value goes through as a string, but when that information gets pulled in from the backend it's often times a number. A good example of this is the SEP ID field, when you create it it's a string. When it comes to the frontend it's there as a number, but then once you update it it's a string again. This is making validation of the existing participant form quite difficult. I think we need to decide on keeping values either as strings on the front end, or not worry about validation for some of the fields that change type.

2020-11-20 21:47 UTC, MikeyManoguerra commented
if you can set the insurer field to empty sting that's the way to go.  It might break the back end update logic. i don't know how the backend handles an empty field for insurer when it was set before. I think thats the implied logic by switching from t to f, they no longer have insurance.  (there won't be a record over time of their changing status, but that's ok for now).

Yea and the number to string issue is going to happen since we are storing the values as inputs. im fine with switching the value to a string before submitting. as long as the update goes through 200

2020-11-24 13:28 UTC, JackRyan1989 reviewed
Changes made

2020-11-24 20:10 UTC, JackRyan1989 commented
@MikeyManoguerra I changed the sep_data model to be a charfield. Let me know if that is no bueno.

2020-11-26 04:30 UTC, MikeyManoguerra commented
So my knee jerk reaction is to say id rather change it on the front end.  but the reason is to maintain numerical integrity from a data perspective.

if stay like this you should do something similar to the clean method i wrote here : https://github.com/CodeForPhilly/prevention-point/blob/master/core/models/visit.py, but compare the incoming value to a regex.

if on the front end, when an existing participant is passed to the `setParticipant` method,  you could 
do something like 
```
@action setParticipant(data){
const {sep} =data
this .participant = {...data, sep: sep ? sep.toString(): ''}
}
```
with the ternary making it extra cautious haha

I feel like the whole thing is going to get an audit from an UX and data perspective, and this might not matter/be wrong. the ssn on this table is char.

2020-11-26 04:39 UTC, MikeyManoguerra commented
@JackRyan1989 https://docs.djangoproject.com/en/3.1/ref/models/instances/#validating-objects

2020-11-26 15:46 UTC, JackRyan1989 commented
@MikeyManoguerra Great suggestion with the ternary. And yeah, I felt not great (smelly) about changing a model to match our validation on the frontend. 
Tested both the update and new participant validation and all worked well. Let me know if you see anything else that should be changed.
Happy Thanksgiving btw!

2020-11-26 18:02 UTC, MikeyManoguerra commented
Happy thanksgiving to you too! Looks good, The only issue i saw was that when the is_insured is false, theres still an insurer FK. but this is a seed / model validation issue, and should be updated there. looks good!

2020-11-26 22:55 UTC, merged