Separate participants store 425
CodeForPhilly/prevention-point pull request #452
Opened 2020-11-27 23:45 UTC by JackRyan1989

@MikeyManoguerra So I created a new store titled "NotificationStore". Currently it just handles the snackbar state. Is there anything else I should move over to this new store from the participant store? Maybe I should make the error message const an observable? 

Also, I can title it something else if need be. Was thinking UtilityStore, ErrorStore or GeneralStore (har har) as options but none felt totally accurate.

2020-11-28 15:22 UTC, MikeyManoguerra commented
general store is funny. I like utility store, use that.

you can move drawer logic and and search observable and their logic over.

error const doesn't need to be bc it is just a string id basically.


one other thing, is it possible to reference the participantstore (or any non root store) in the constructor? if you can't find an easy answer it's no big deal but it would be better not to have to drill down so much

2020-11-29 02:12 UTC, JackRyan1989 commented
@MikeyManoguerra I renamed the new store to UtilityStore as recommended. I also moved over the search sidebar stuff. 

Weirdly, I couldn't get the UtilityStore to work when put into the constructor. The error I got was that that rootStore was not defined. Which is throwing me for a loop given this stack overflow exchange: https://stackoverflow.com/questions/44928645/how-can-i-access-mobx-store-in-another-mobx-store#44928890

Not sure if it has to do with how we're passing the context in or not.

2020-12-01 02:53 UTC, MikeyManoguerra commented on frontend/src/components/VisitRouter/index.js
> +          notificationStore.setSnackbarState(
missed an update here

2020-12-01 02:53 UTC, MikeyManoguerra commented on frontend/src/components/VisitRouter/index.js
> +      notificationStore.setSnackbarState(handleError(err))
and here

2020-12-01 02:56 UTC, MikeyManoguerra requested changes
Looks good except for the old name in the visit router.

2020-12-01 13:30 UTC, JackRyan1989 commented on frontend/src/components/VisitRouter/index.js
> +          notificationStore.setSnackbarState(
Updated, thanks for catching!

2020-12-01 13:30 UTC, JackRyan1989 commented on frontend/src/components/VisitRouter/index.js
> +      notificationStore.setSnackbarState(handleError(err))
Updated, thanks for catching!

2020-12-01 14:11 UTC, MikeyManoguerra approved these changes

2020-12-01 14:47 UTC, merged